version: '3.9'

services:
  some-name:
    image: postgres
    container_name: some-name
    ports:
      - "5434:5432"
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: crypto
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-crypto
    ports:
      - "6379:6379"