version: '3.9'

services:
  postgresql:
    image: postgres
    container_name: avtoria
    ports:
      - "5434:5433"
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DATABASE: avtoria
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-avtoria
    ports:
      - "6379:6379"