export const users = [
  {
    _id: '64e52d434d29f4cdaed5f44e',
    index: 0,
    guid: '4156548c-d8dc-4e3d-8e97-c1036632f524',
    isActive: true,
    balance: '$3,085.78',
    picture: 'http://placehold.it/32x32',
    age: 21,
    eyeColor: 'blue',
    name: 'Moreno Shaw',
    gender: 'male',
    company: 'NIMON',
    email: 'morenoshaw@nimon.com',
    phone: '+1 (966) 441-2658',
    address: '355 Wilson Avenue, Harrison, New Jersey, 1991',
    about:
      'Consectetur culpa commodo commodo ea do nisi eu Lorem cillum in amet nostrud veniam. Ad nulla dolor nisi reprehenderit consectetur. Deserunt ut esse elit anim veniam quis amet fugiat reprehenderit fugiat fugiat magna do. Voluptate veniam do non Lorem ullamco. Ut eu irure aliquip reprehenderit nulla cillum minim proident. Qui irure et ad Lorem cupidatat commodo aliqua incididunt nisi incididunt cillum in.\r\n',
    registered: '2022-12-16T11:25:22 -02:00',
    latitude: -36.791193,
    longitude: -153.481979,
    tags: ['qui', 'nisi', 'aliqua', 'magna', 'et', 'adipisicing', 'aliqua'],
    friends: [
      {
        id: 0,
        name: 'Marina West',
      },
      {
        id: 1,
        name: 'Trisha House',
      },
      {
        id: 2,
        name: 'Dunlap Larson',
      },
    ],
    greeting: 'Hello, Moreno Shaw! You have 10 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '64e52d431fce35e864e5e997',
    index: 1,
    guid: '5aec4497-322b-4f9e-8ed3-6d88181753e3',
    isActive: true,
    balance: '$1,380.54',
    picture: 'http://placehold.it/32x32',
    age: 33,
    eyeColor: 'green',
    name: 'Jewell Johnston',
    gender: 'female',
    company: 'ARCHITAX',
    email: 'jewelljohnston@architax.com',
    phone: '+1 (914) 420-3081',
    address: '298 Cambridge Place, Wright, Wisconsin, 4819',
    about:
      'Elit irure exercitation laborum nisi duis adipisicing aliqua culpa et eiusmod sunt. Consequat est labore nostrud est. Tempor mollit magna consequat aute. Cillum Lorem ex tempor mollit aliquip commodo nisi mollit proident consequat. Ullamco anim sit excepteur aliqua sunt quis sunt amet sit quis fugiat. Esse ipsum sit aute incididunt occaecat cillum cillum. Veniam adipisicing proident eiusmod anim nulla incididunt reprehenderit nostrud voluptate exercitation.\r\n',
    registered: '2017-12-18T09:29:40 -02:00',
    latitude: 10.070076,
    longitude: -24.040338,
    tags: ['ad', 'amet', 'tempor', 'laboris', 'anim', 'proident', 'mollit'],
    friends: [
      {
        id: 0,
        name: 'Doreen Sweet',
      },
      {
        id: 1,
        name: 'Long Sexton',
      },
      {
        id: 2,
        name: 'Allison Brock',
      },
    ],
    greeting: 'Hello, Jewell Johnston! You have 5 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '64e52d43d6a4217dd2a164d7',
    index: 2,
    guid: '8d24c608-153e-49fb-a929-f2c44028b2e6',
    isActive: true,
    balance: '$2,171.71',
    picture: 'http://placehold.it/32x32',
    age: 28,
    eyeColor: 'brown',
    name: 'Garner Hammond',
    gender: 'male',
    company: 'CYTRAK',
    email: 'garnerhammond@cytrak.com',
    phone: '+1 (954) 529-2572',
    address: '104 Erasmus Street, Tedrow, Utah, 3148',
    about:
      'Minim ex proident deserunt irure. Consequat id minim nisi nostrud irure. Pariatur aliqua culpa duis sunt laborum deserunt dolor labore culpa aute ea. Deserunt commodo veniam cupidatat in.\r\n',
    registered: '2018-02-28T07:44:00 -02:00',
    latitude: -72.904589,
    longitude: -151.030454,
    tags: [
      'ex',
      'reprehenderit',
      'pariatur',
      'deserunt',
      'est',
      'aute',
      'sint',
    ],
    friends: [
      {
        id: 0,
        name: 'Bass Mcgowan',
      },
      {
        id: 1,
        name: 'Adrian Berry',
      },
      {
        id: 2,
        name: 'Susanna Haynes',
      },
    ],
    greeting: 'Hello, Garner Hammond! You have 5 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '64e52d43e85d440854d35b58',
    index: 3,
    guid: '9a1f171f-b680-4b79-98ea-80d10b1bd6b7',
    isActive: true,
    balance: '$3,193.96',
    picture: 'http://placehold.it/32x32',
    age: 20,
    eyeColor: 'blue',
    name: 'Wilkerson Harrison',
    gender: 'male',
    company: 'MEGALL',
    email: 'wilkersonharrison@megall.com',
    phone: '+1 (967) 554-3329',
    address: '768 Crawford Avenue, Geyserville, New York, 3450',
    about:
      'Reprehenderit amet esse reprehenderit ex occaecat occaecat dolore cupidatat occaecat qui consectetur ad officia ullamco. Nisi ex eu occaecat sit qui esse adipisicing sit. Ut proident in officia laborum. Labore esse mollit quis veniam veniam dolor. Amet aliqua consectetur minim officia ipsum cupidatat enim enim dolore qui quis. Tempor excepteur mollit proident laborum ullamco cupidatat enim aliquip voluptate fugiat non id nisi dolore. Laboris enim sint amet officia ea.\r\n',
    registered: '2014-02-28T04:54:25 -02:00',
    latitude: 60.615899,
    longitude: -114.304678,
    tags: [
      'occaecat',
      'ad',
      'officia',
      'commodo',
      'adipisicing',
      'laboris',
      'sunt',
    ],
    friends: [
      {
        id: 0,
        name: 'Sylvia Mckee',
      },
      {
        id: 1,
        name: 'Mandy Lester',
      },
      {
        id: 2,
        name: 'Latoya Lambert',
      },
    ],
    greeting: 'Hello, Wilkerson Harrison! You have 4 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '64e52d437f9fef971a521cba',
    index: 4,
    guid: '95b6ce11-a207-4ec0-92fa-4a5dd3d750d4',
    isActive: false,
    balance: '$1,189.91',
    picture: 'http://placehold.it/32x32',
    age: 23,
    eyeColor: 'blue',
    name: 'Pierce Justice',
    gender: 'male',
    company: 'APPLIDEC',
    email: 'piercejustice@applidec.com',
    phone: '+1 (837) 461-2112',
    address: '927 Kenilworth Place, Boyd, Federated States Of Micronesia, 1438',
    about:
      'Lorem labore esse duis do anim consequat sint amet non duis officia sit eiusmod. Amet consequat tempor do ut ullamco eiusmod excepteur adipisicing. Voluptate labore mollit incididunt veniam aute fugiat Lorem laboris nulla irure eiusmod. Incididunt consequat ad ullamco culpa magna cupidatat aliquip nulla ut irure do reprehenderit. Reprehenderit nostrud culpa labore nisi consectetur tempor aute magna.\r\n',
    registered: '2017-08-02T09:29:01 -03:00',
    latitude: 1.750377,
    longitude: -88.095692,
    tags: ['do', 'ut', 'pariatur', 'nostrud', 'laboris', 'aliquip', 'laboris'],
    friends: [
      {
        id: 0,
        name: 'Martha Wagner',
      },
      {
        id: 1,
        name: 'Shaffer Gutierrez',
      },
      {
        id: 2,
        name: 'Avis Sims',
      },
    ],
    greeting: 'Hello, Pierce Justice! You have 7 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '64e52d431dad99dbe16e9c65',
    index: 5,
    guid: 'ce371260-5ce2-4955-b939-efd02121a293',
    isActive: true,
    balance: '$1,641.86',
    picture: 'http://placehold.it/32x32',
    age: 32,
    eyeColor: 'brown',
    name: 'Kent Cole',
    gender: 'male',
    company: 'TELLIFLY',
    email: 'kentcole@tellifly.com',
    phone: '+1 (961) 600-2166',
    address: '433 Hewes Street, Sardis, Virginia, 9424',
    about:
      'Veniam pariatur cillum qui ad laborum ullamco non enim do officia. Officia ullamco deserunt culpa minim esse consectetur id do minim. Irure dolore irure ex eiusmod cupidatat eiusmod Lorem proident.\r\n',
    registered: '2016-04-15T11:44:07 -03:00',
    latitude: 62.796654,
    longitude: -104.459991,
    tags: ['qui', 'elit', 'magna', 'sunt', 'ullamco', 'nostrud', 'occaecat'],
    friends: [
      {
        id: 0,
        name: 'Gomez Wilson',
      },
      {
        id: 1,
        name: 'Rodgers Pruitt',
      },
      {
        id: 2,
        name: 'Orr Ayers',
      },
    ],
    greeting: 'Hello, Kent Cole! You have 4 unread messages.',
    favoriteFruit: 'banana',
  },
];
