export enum AcuraEnum {
  ILX = 'ILX',
  MDX = 'MDX',
  NSX = 'NSX',
  RDX = 'RDX',
  RLX = 'RLX',
  TLX = 'TLX',
}
export enum AlfaRomeoEnum {
  GIULIA = 'Giulia',
  STELVIO = 'Stelvio',
  TONALE = 'Tonale',
  MITO = 'MiTo',
  GIULIETTA = 'Giulietta',
}
export enum AudiEnum {
  A1 = 'A1',
  A3 = 'A3',
  A4 = 'A4',
  A5 = 'A5',
  A6 = 'A6',
  A7 = 'A7',
  A8 = 'A8',
  Q2 = 'Q2',
  Q3 = 'Q3',
  Q5 = 'Q5',
  Q7 = 'Q7',
  Q8 = 'Q8',
  R8 = 'R8',
  RS3 = 'RS 3',
  RS4 = 'RS 4',
  RS5 = 'RS 5',
  RS6 = 'RS 6',
  RS7 = 'RS 7',
  RSQ3 = 'RS Q3',
  RSQ5 = 'RS Q5',
  RSQ7 = 'RS Q7',
  TT = 'TT',
  TTS = 'TTS',
  TTRS = 'TT RS',
}
export enum BMWEnum {
  _1_SERIES = '1 Series',
  _2_SERIES = '2 Series',
  _3_SERIES = '3 Series',
  _4_SERIES = '4 Series',
  _5_SERIES = '5 Series',
  _6_SERIES = '6 Series',
  _7_SERIES = '7 Series',
  X1 = 'X1',
  X2 = 'X2',
  X3 = 'X3',
  X4 = 'X4',
  X5 = 'X5',
  X6 = 'X6',
  X7 = 'X7',
  M2 = 'M2',
  M3 = 'M3',
  M4 = 'M4',
  M5 = 'M5',
  M6 = 'M6',
  M8 = 'M8',
  Z4 = 'Z4',
}
export enum CadillacEnum {
  XT4 = 'XT4',
  XT5 = 'XT5',
  XT6 = 'XT6',
  XT7 = 'XT7',
  ESCALADE = 'Escalade',
}
export enum ChevroletEnum {
  AVEO = 'Aveo',
  CAMARO = 'Camaro',
  CAPTIVA = 'Captiva',
  COLORADO = 'Colorado',
  CRUZE = 'Cruze',
  EQUINOX = 'Equinox',
  IMPALA = 'Impala',
  MALIBU = 'Malibu',
  SPARK = 'Spark',
  TAHOE = 'Tahoe',
  TRAX = 'Trax',
  VOLT = 'Volt',
}
export enum ChryslerEnum {
  AIR_GRAND = 'Air_Grand',
  ASPIRE = 'Aspire',
  CIRRUS = 'Cirrus',
  CROSSFIRE = 'Crossfire',
  DODGE = 'Dodge',
  DURANGO = 'Durango',
  GRAND_VOYAGER = 'Grand_Voyager',
  PT_CRUISER = 'PT_Cruiser',
  SEBRING = 'Sebring',
  TOWN_AND_COUNTRY = 'Town_And_Country',
  VOYAGER = 'Voyager',
}
export enum CitroënEnum {
  C1 = 'C1',
  C3 = 'C3',
  C3_Aircross = 'C3 Aircross',
  C4 = 'C4',
  C4_Cactus = 'C4 Cactus',
  C5_Aircross = 'C5 Aircross',
  C5 = 'C5',
  DS3 = 'DS3',
  DS4 = 'DS4',
  DS5 = 'DS5',
  Jumper = 'Jumper',
  Nemo = 'Nemo',
  SpaceTourer = 'SpaceTourer',
  Xsara_Picasso = 'Xsara Picasso',
}
export enum DaciaEnum {
  Sandero = 'Sandero',
  Logan = 'Logan',
  Duster = 'Duster',
  Jogger = 'Jogger',
  Spring = 'Spring',
  Bigster = 'Bigster',
}
export enum DaewooEnum {
  Lanos = 'Lanos',
  Nexia = 'Nexia',
  Espero = 'Espero',
  Matiz = 'Matiz',
  Leganza = 'Leganza',
  Nubira = 'Nubira',
  Tacuma = 'Tacuma',
  LeganzaII = 'Leganza II',
  MatizII = 'Matiz II',
  Kalos = 'Kalos',
  Lacetti = 'Lacetti',
  NubiraII = 'Nubira II',
  Sens = 'Sens',
  LanosII = 'Lanos II',
}
export enum DaihatsuEnum {
  Altis = 'Altis',
  Applause = 'Applause',
  Atrai = 'Atrai',
  Bee = 'Bee',
  Bongo = 'Bongo',
  Ceria = 'Ceria',
  Charade = 'Charade',
  Charmant = 'Charmant',
  Compagno = 'Compagno',
  Cuore = 'Cuore',
  Hijet = 'Hijet',
  Materia = 'Materia',
  Mira = 'Mira',
  Mirae = 'Mira e:S',
  MiraGino = 'Mira Gino',
  MiraiLINE = 'Mira i-LINE',
  MiraTRXX = 'Mira TR-XX',
  Move = 'Move',
  Rocky = 'Rocky',
  Sirion = 'Sirion',
  Terios = 'Terios',
  Tanto = 'Tanto',
  TeriosKid = 'Terios Kid',
  YRV = 'YRV',
}
export enum DodgeEnum {
  Challenger = 'Challenger',
  Charger = 'Charger',
  DART = 'DART',
  Durango = 'Durango',
  Journey = 'Journey',
  Magnum = 'Magnum',
  Nitro = 'Nitro',
  Ram = 'Ram',
  Stealth = 'Stealth',
  Viper = 'Viper',
}
export enum FiatEnum {
  Albea = 'Albea',
  Argo = 'Argo',
  Bravo = 'Bravo',
  Cinquecento = 'Cinquecento',
  Doblo = 'Doblo',
  Ducato = 'Ducato',
  Fiorino = 'Fiorino',
  Freemont = 'Freemont',
  Idea = 'Idea',
  Intercity = 'Intercity',
  Iveco = 'Iveco',
  Panda = 'Panda',
  Palio = 'Palio',
  Punto = 'Punto',
  Qubo = 'Qubo',
  SEICENTO = 'SEICENTO',
  Strada = 'Strada',
  Toro = 'Toro',
  Tipo = 'Tipo',
  Uno = 'Uno',
}
export enum FordEnum {
  Fiesta = 'Fiesta',
  Focus = 'Focus',
  Fusion = 'Fusion',
  EcoSport = 'EcoSport',
  Bronco = 'Bronco',
  Mustang = 'Mustang',
  Explorer = 'Explorer',
  Edge = 'Edge',
  Escape = 'Escape',
  Maverick = 'Maverick',
  Ranger = 'Ranger',
  SuperDuty = 'Super Duty',
  F150 = 'F-150',
}
export enum GeelyEnum {
  Atlas = 'Atlas',
  Emgrand = 'Emgrand',
  Coolray = 'Coolray',
  Tugella = 'Tugella',
  Vision = 'Vision',
  Borui = 'Borui',
  Xingyue = 'Xingyue',
  Binrui = 'Binrui',
  Jiaji = 'Jiaji',
  Okavango = 'Okavango',
  Icon = 'Icon',
  Preface = 'Preface',
  GlobalEagle = 'Global Eagle',
  LynkCo = 'Lynk & Co',
  Zeekr = 'Zeekr',
}
export enum GMCEnum {
  Canyon = 'Canyon',
  Sierra = 'Sierra',
  Terrain = 'Terrain',
  Acadia = 'Acadia',
  Yukon = 'Yukon',
  YukonXL = 'Yukon XL',
  HummerEV = 'Hummer EV',
  HummerEVSUV = 'Hummer EV SUV',
}
export enum MercedesEnum {
  GLA = 'GLA',
  AClass = 'A-Class',
  BClass = 'B-Class',
  CClass = 'C-Class',
  EClass = 'E-Class',
  SClass = 'S-Class',
  CLS = 'CLS',
  GLC = 'GLC',
  GLE = 'GLE',
  GLS = 'GLS',
  GClass = 'G-Class',
  AMGGT = 'AMG GT',
  EQC = 'EQC',
  EQS = 'EQS',
}
export enum HondaEnum {
  Civic = 'Civic',
  Accord = 'Accord',
  Insight = 'Insight',
  Clarity = 'Clarity',
  HRV = 'HR-V',
  Pilot = 'Pilot',
  CRV = 'CR-V',
  Odyssey = 'Odyssey',
  Fit = 'Fit',
  Ridgeline = 'Ridgeline',
  Passport = 'Passport',
  AccordHybrid = 'Accord Hybrid',
  ClarityFuelCell = 'Clarity Fuel Cell',
}
export enum HyundaiEnum {
  Elantra = 'Elantra',
  Kona = 'Kona',
  Tucson = 'Tucson',
  SantaFe = 'Santa Fe',
  Palisade = 'Palisade',
  Ioniq = 'Ioniq',
  Ioniq5 = 'Ioniq 5',
  IoniqHybrid = 'Ioniq Hybrid',
  IoniqPHEV = 'Ioniq PHEV',
  Sonata = 'Sonata',
  Genesis = 'Genesis',
  Nexo = 'Nexo',
  Venue = 'Venue',
  SantaCruz = 'Santa Cruz',
}
export enum InfinitiEnum {
  Q50 = 'Q50',
  Q60 = 'Q60',
  QX50 = 'QX50',
  QX60 = 'QX60',
  QX80 = 'QX80',
  QX70 = 'QX70',
  QX55 = 'QX55',
  QX60Monograph = 'QX60 Monograph',
  QX80Monograph = 'QX80 Monograph',
  QX50Hybrid = 'QX50 Hybrid',
  QX60Hybrid = 'QX60 Hybrid',
  QX80Hybrid = 'QX80 Hybrid',
}
